version: "3"

services:
  node:
    build:
      context: ./.docker/node
    container_name: appnode
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    build: ./.docker/nginx
    container_name: node_nginx
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - node

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: node_db
    restart: always
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
